language: node_js
node_js:
  - 12
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  target_branch: deploy
  on:
    branch: master
